### PR TITLE
Update node deps

### PR DESCRIPTION
**Pull request by TimothyGu**
Two questions:

1. Should I check in the updated node_modules? It is common for Node.js projects to *not* check it in.
2. Should I merge this into release/3.3 or will the project do it?

### CODE REVIEW

**Comment by hegemonic** [comment]
Updating the dependencies is a somewhat complicated process, because we also need to support non-Node.js users.

If you explain which dependencies you want to update and why, I can take care of the updates.

**Comment by TimothyGu** [comment]
@hegemonic By non-Node.js users, do you mean Rhino only? This PR doesn't actually work for Rhino for now but I have a patch for that (the shim needs some updating). If there is anything else needed to fix I can do that.

The main reason I did this was the way-too-old async version causing some conflicts in my system.

**Comment by TimothyGu** [comment]
OK just fixed the issue on Rhino. All tests are passing again.

**Comment by hegemonic** [comment]
Fixed on master and the releases/3.3 branch by commit a2ce6a79ad314768cafa417a4fe02da3b33144a8. (As I said, it's faster to just update the dependencies than to explain exactly how to do it.)

Thanks for explaining the rationale, and for the `process.platform` fix.

**Comment by TimothyGu** [comment]
@hegemonic Cool thanks.

**Pull request closed without merging**
