### PR TITLE
fix: Don't depend on taffydb #961

### PR DESCRIPTION
**Pull request by popomore**
Copy to deps/taffydb #961

### CODE REVIEW

**Comment by agirorn** [comment]
Why not install from npm https://www.npmjs.com/package/taffydb ?

**Comment by popomore** [comment]
It's not compatible with the version from npm, and it donesn't maintain.

**Comment by popomore** [comment]
https://github.com/jsdoc3/jsdoc/issues/961#issuecomment-100739372

**Comment by popomore** [comment]
Any one can review it?

**Comment by popomore** [comment]
ping @hegemonic

**Comment by hegemonic** [comment]
Sorry, but I can't merge this for the reasons described in [this comment](https://github.com/jsdoc3/jsdoc/issues/961#issuecomment-244245221).

**Pull request closed without merging**
