### PR TITLE
Update README.md to include gulp task

### PR DESCRIPTION
**Pull request by mlucool**
This should replace the suggestion from https://github.com/jsdoc3/jsdoc/pull/874#issuecomment-166071107

### CODE REVIEW

**Comment by mlucool** [comment]
@hegemonic any feedback?

**Comment by mlucool** [comment]
As an FYI: https://github.com/jsBoot/gulp-jsdoc has been formally deprecated in favor of this. See: https://github.com/jsBoot/gulp-jsdoc/pull/32

**Comment by mlucool** [comment]
Can this be merged?

**Comment by hegemonic** [comment]
Merged. Sorry for the lengthy delay.

**Comment by mlucool** [comment]
:+1:

**Pull request merged**
