### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by bjornharrtell**
Except `espree` because I don't know how to fix the breaking changes.

Started this to scratch the itch that `npm` warned that wrench was deprecated in favor of `fs-extra` but ended up going through all dependencies.

### CODE REVIEW

**Comment by tripu** [comment]
Reviewing and merging this would be good.

(Note that latest `fs-extra` is `0.30.0` now.)

**Comment by 75lb** [comment]
i have applied this patch to my [jsdoc fork](https://github.com/jsdoc2md/jsdoc), all tests pass, the tool works perfectly and the deprecation warnings are gone.. therefore, this patch is now live in [jsdoc2md](https://github.com/jsdoc2md/jsdoc-to-markdown).. thanks!

**Comment by thegiantbeast** [comment]
Was this PR forgotten?

It would be awesome if it could be merged ASAP (right after the conflicts are solved ofc).

**Comment by 75lb** [comment]
@thegiantbeast Take a look at the project pulse, recent commits, recent issue updates by the maintainer etc. - it's clear the project is dead.. i suggest you fork the project and apply the patch yourself, that's what i did.

**Comment by 75lb** [comment]
@thegiantbeast or install the fork i linked to above, that already has the patch.

**Comment by hegemonic** [comment]
Merged to master and releases/3.4. Thanks for doing this!

**Pull request merged**
