### PR TITLE
feat(Readme): Add minami template to README.md

### PR DESCRIPTION
**Pull request by Nijikokun**
Added link to [minami](https://github.com/Nijikokun/minami) under **Templates** in `Readme.md`

### CODE REVIEW

**Comment by hegemonic** [comment]
@Nijikokun Very nice template!

I have one concern: It looks like your template is based on JSDoc's default template. That means it should use the Apache 2.0 license (just like JSDoc), not the MIT license. Would you mind updating the license before I merge your pull request?

**Comment by Nijikokun** [comment]
@hegemonic thanks, and I don't mind at all, done :)

**Comment by Nijikokun** [comment]
License has been updated @hegemonic :+1:

**Comment by hegemonic** [comment]
Merged. Thanks for correcting the license!

**Pull request merged**
